# Site settings
title: Betrouwbare Boekhoudkoppelingen
email: info@boekhoudkoppelingen.nl
description: > # this means to ignore newlines until "baseurl:"
  Koppel je boekhoudpakket bijvoorbeeld met een CMS, website, of facturatiepakket
  met onze handige koppelingen.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: combidesk
github_username:  combidesk

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 3
paginate_path: "blog/page:num"

collections:
  categorieen:
  koppelingen:
    output: true
    permalink: /:collection/:name
  koppeling:
    output: true
    permalink: /:collection/:name
